services:
  suara:
    build: .
    extends:
      file: compose.yml
      service: suara
    command: npm run dev
    environment:
      - ENVIRONMENT=dev
    volumes:
      - type: bind
        source: ./
        target: /app
  mongo:
    ports:
      - "27017:27017"
    image: "mongo:latest"
    networks:
      - suara_network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "2.0"
