services:
  suara:
    build: .
    command: ${ENVIRONMENT_COMMAND}
    environment:
      - MONGO_URL=${MONGO_URL}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
    volumes:
      - type: bind
        source: ./
        target: /app
  mongo:
    ports:
      - "27017:27017"
    image: "mongo:latest"

networks:
  suara-network:
    driver: bridge
