name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Image build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: betester/suara:${GITHUB_REF_NAME}
      - name: SSH and SCP to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            scp -i /root/.ssh/id_rsa compose.prod.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/compose.prod.yml

            ssh -i /root/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
              # Set environment variables
              export IMAGE_VERSION=${GITHUB_REF_NAME}
              export MONGO_URL=${{ secrets.MONGO_URL }}
              export DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
              export DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}
              
              # Run Docker Compose
              docker-compose -f ~/compose.prod.yml up -d
            EOF
