name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Image build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: betester/suara:${{ github.ref_name }}

      - name: SCP to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "compose.prod.yml,compose.yml"
          target: "~"

      - name: SSH to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            # Set environment variables
            echo "IMAGE_VERSION=${{ github.ref_name }}" > ~/.env
            echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> ~/.env
            echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" >> ~/.env
            echo "export DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}"  >> ~/.env
            echo "export GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}" >> ~/.env 
            ls -a
            # Run Docker Compose
            docker-compose -f ~/compose.yml -f ~/compose.prod.yml up -d
            # remove any unused docker container, cache and so on
            docker-compose system prune -a -f
